### ISSUE TITLE
[Minor Improvement] Instead of static image in Readme, create practical example and make gif of it or mini video and put that instead of static image

### ISSUE THREAD

**Issue by HakaishinShwet** [theyashwanthsai/Devyan#4]
This will help in demonstrating the actual working of project and how it perform actions to solve or create things so this will make things much easier for others to understand who are interested in such projects :-)). Rest i will also try this soon

**Comment by theyashwanthsai** [comment]
Yup, i wanted to embed the video which i had in my tweet to readme but then forgot about, The repository is suddenly getting noticed so i will have to do that

**Comment by theyashwanthsai** [comment]
Added :)
